'\" t
.\"     Title: apt-cyg
.\"    Author: Brian Inglis
.\"      Date: 10 July 2019
.\"    Manual: apt-cyg
.\"    Source: apt-cyg 1.0
.\"  Language: English
.\"
.TH "apt\-cyg" "8" "\ 10\ \&July\ \&2019" "apt\-cyg\ 1\&.0" "apt\-cyg"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt\-cyg \- Cygwin package manager utility

.SH "SYNOPSIS"
.HP \w'\fBapt-cyg\fR\ 'u
\fBapt-cyg\fR [\fB-?\fR|\fB-h\fR|\fB\-\-h\fR[\fBelp\fR]|\fB\-V\fR|\fB-v\fR|\fB-\-v\fR[\fBersion\fR]]
[\fBl\fR[\fBist\fR[\fBa\fR[\fBll\fR]]]\ \fR[\fIpkg\fR...] |
[\fBs\fR[\fBhow\fR] | \fBl\fR[\fBist\fR]\fBf\fR[\fBiles\fR] |
\fBi\fR[\fBnstall\fR]\ [\fB-n\fR|\fB\-\-nod\fR[\fBeps\fR]]\ [\fB-p\fR|\fB\-\-nop\fR[\fBick\fR]]\ [\fB-s\fR|\fB\-\-nos\fR[\fBcripts\fR]] |
\fBso\fR[\fBurce\fR]\ [\fB-b\fR|\fB\-\-b\fR[\fBuild\fR]|\fB-c\fR|\fB\-\-c\fR[\fBompile\fR]|\fB-d\fR|\fB\-\-d\fR[\fBownload\fR[\fB\-only\fR]]] |
\fBdo\fR[\fBwnload\fR] | \fBre\fR[\fBmove\fR] | \fBde\fR[\fBpends\fR] | \fBrd\fR[\fBepends\fR]]\ \fIpkg\fR\... |
\fBse\fR[\fBarch\fR[\fBa\fR[\fBll\fR]]]\ \fIfile\fR... | \fBcat\fR[\fBegor\fR[\fBy\fR|\fBies\fR]]\ [\fIcat\fR...] |
\fBu\fR[\fBpdate\fR] | \fBm\fR[\fBirror\fR\] [\fIURL\fR] | \fBcac\fR[\fBhe\fR]\ [\fIdirectory\fR]]

.SH "DESCRIPTION"
.PP
\fBapt\-cyg\fR
is a package management utility that tracks installed packages on a Cygwin system.
Invoking apt\-cyg involves specifying an operation with any potential options and targets to operate on.
A target is either a package name, file name, search string, URL, or directory.
Targets can be provided as command line arguments.

.SH "OPERATIONS"
.PP
\fBl\fR[\fBist\fR[\fBa\fR[\fBll\fR]]]\ \fR[\fIpkg\fR...]
.RS 4
Search for package names that match shell patterns.
If no package names are provided in the command line, all installed packages will be listed.
If
\fBl\fR[\fBist\fR]\fBa\fR[\fBll\fR]
is used, or no packages are found by list, searches the master package list (in setup.ini).
.RE
.PP
\fBs\fR[\fBhow\fR]\ \fIpkg\fR...
.RS 4
Display information on given package name(s).
.RE
.PP
\fBl\fR[\fBist\fR]\fBf\fR[\fBiles\fR]\ \fIpkg\fR...
.RS 4
List all files owned by a given package. Multiple packages can be specified
on the command line.
.RE
.PP
\fBi\fR[\fBnstall\fR]\ \fIpkg\fR...
.RS 4
Install package(s) and any dependencies.
.RE
.PP
\fBso\fR[\fBurce\fR]\ \fIpkg\fR...
.RS 4
Retrieve package source(s) from the server into package directory created
under current directory and unpack under the package directory.
.RE
.PP
\fBdo\fR[\fBwnload\fR]\ \fIpkg\fR...
.RS 4
Retrieve package(s) from the server, but do not install/upgrade anything.
.RE
.PP
\fBre\fR[\fBmove\fR]\ \fIpkg\fR...
.RS 4
Remove package(s) from the system.
.RE
.PP
\fBde\fR[\fBpends\fR]\ \fIpkg\fR...
.RS 4
Produce a tree of all dependencies for a package.
.RE
.PP
\fBrd\fR[\fBepends\fR]\ \fIpkg\fR...
.RS 4
Produce a tree of packages that depend on the named package.
.RE
.PP
\fBse\fR[\fBarch\fR[\fBa\fR[\fBll\fR]]]\ \fIfile\fR...
.RS 4
Search for packages that own the specified file(s).
The path can be relative or absolute, and one or more files can be specified.
If
\fBse\fR[\fBarch\fR]\fBa\fR[\fBll\fR]
is used searches cygwin.com for packages that own the specified file(s).
.RE
.PP
\fBcat\fR[\fBegor\fR[\fBy\fR|\fBies\fR]]\ [\fIcat\fR...]
.RS 4
Display all packages that are members of a named category.
If no category is provided in the command line, all categories used will be listed.
.RE
.PP
\fBu\fR[\fBpdate\fR]
.RS 4
Download a fresh copy of the master package list (setup.ini) from the mirror.
.RE
.PP
\fBm\fR[\fBirror\fR]\ [\fIURL\fR]
.RS 4
Set the mirror:
a full URL to a location where the database, packages, and signatures
for this repository can be found.
If no URL is provided, display the current mirror.
.RE
.PP
\fBcac\fR[\fBhe\fR]\ [\fIdirectory\fR]
.RS 4
Set the package cache directory.
Unix and Windows forms are accepted, as well as absolute or regular paths.
If no directory is provided, display current cache.
If a package to install is not found in the cache directory,
it will be downloaded.

.SH "OPTIONS"
.RE
.PP
\fB\-b\fR|\fB\-\-b\fR[\fBuild\fR]|\fB\-c\fR|\fB\-\-c\fR[\fBompile\fR]
.RS 4
With source: install any build dependencies;
if cygport is part of the package,
include cygport and any of its build dependencies,
and build package using cygport;
otherwise try to configure, then try to make;
if cygport is not part of the package, build dependencies may be missing,
and need to be installed manually.
.RE
.PP
\fB\-d\fR|\fB\-\-d\fR[\fBownload\fR[\fB\-only\fR]]
.RS 4
With source: just download and do not unpack source package.
.RE
.PP
\fB\-i\fR|\fB\-\-i\fR[\fBnstalled\fR]
.RS 4
With list: display only installed packages.
.RE
.PP
\fB\-n\fR|\fB\-\-nod\fR[\fBeps\fR]
.RS 4
Specify this option to skip all dependency checks,
and not download or install packages 
on which specified packages are dependent.
.RE
.PP
\fB\-p\fR|\fB\-\-nop\fR[\fBick\fR]
.RS 4
Internal option for install of a package dependency.
.RE
.PP
\fB\-s\fR|\fB\-\-nos\fR[\fBcripts\fR]
.RS 4
Specify this option to skip running any preremove or postinstall scripts.
Used internally during install to defer running postinstall scripts until all
requested packages and dependencies have been installed.
.RE
.PP
\fB\-u\fR|\fB\-\-u\fR[\fBpgradable\fR]
.RS 4
With list: display only outdated packages.
.RE
.PP
\fB\-?\fR|\fB\-h\fR|\fB\-\-h\fR[\fBelp\fR]
.RS 4
Display usage and exit.
.RE
.PP
\fB\-V\fR|\fB\-v\fR|\fB\-\-v\fR[\fBersion\fR]
.RS 4
Display version and exit.
.RE

.SH "DIAGNOSTICS"
.PP
\fBapt\-cyg\fR
returns zero on normal operation, non-zero on error\&.
.RE

.SH "AUTHORS"
.PP
\fBStephen Jungels\fR \- original code @ https://github.com/transcode\-open/apt\-cyg
.br
\fBErnie Rasta\fR \- arch and xz support
.br
\fBLeszek Cimala\fR \- docs
.br
\fBStephen Lang\fR \- fixes and docs
.br
\fBRyan Duryea\fR \- mirror, setup.ini download fixes
.br
\fBSteven Penny\fR \- fixes, add commands, options, functions
.br
\fBLoïc Corbasson\fR \- licence
.br
\fBBrian Inglis\fR \- postinstall fixes, source, man page, authors, upgradable
.RS 4
.RE
